var a = 25;
console.log(typeof a);
var fname = "prakash";
console.log(typeof fname);
var ismarried = true;
console.log(typeof ismarried);
var phone = null;
console.log(typeof phone);
let b;
console.log(typeof b);
const s1 = symbol();
console.log(s1);
const s2 = symbol();
console.log(s2);
console.log(s1 == s2);
var courses = ["c", "c++", "python"];
console.log(typeof courses);
var student = { name: "prakash", id: 102 };
console.log(student);
console.log(typeof student);
